### ISSUE TITLE
adb under linux can connect, uad-ui not

### ISSUE THREAD

**Issue by githluapb** [orgua/universal-android-debloater-UI#2]
I get the following error:

Traceback (most recent call last):
  File "/home/theo/universal-android-debloater-UI/framework_dearpygui.py", line 97, in connect_button_callback
    adb_fw.connect_device_usb()
  File "/home/theo/universal-android-debloater-UI/framework_adb.py", line 58, in connect_device_usb
    device.connect(rsa_keys=[signer], auth_timeout_s=30)
  File "/home/theo/.local/lib/python3.7/site-packages/adb_shell/adb_device.py", line 242, in connect
    self._transport.connect(transport_timeout_s)
  File "/home/theo/.local/lib/python3.7/site-packages/adb_shell/transport/usb_transport.py", line 249, in connect
    self._transport.claimInterface(self._interface_number)
  File "/home/theo/.local/lib/python3.7/site-packages/usb1/__init__.py", line 1169, in claimInterface
    libusb1.libusb_claim_interface(self.__handle, interface),
  File "/home/theo/.local/lib/python3.7/site-packages/usb1/__init__.py", line 127, in mayRaiseUSBError
    __raiseUSBError(value)
  File "/home/theo/.local/lib/python3.7/site-packages/usb1/__init__.py", line 119, in raiseUSBError
    raise __STATUS_TO_EXCEPTION_DICT.get(value, __USBError)(value)
usb1.USBErrorBusy: LIBUSB_ERROR_BUSY [-6]
Exception: Line: 152 	Callable failed

**Comment by githluapb** [comment]
Worked after reboot.
